export const lightTheme = {
  mode: "light",
  colors: {
    background: "#f4f4f4ff",
    cardBackground: "#e9d5e3ff", //"#d8becbff",
    inputBackground: "#efe1ebff",
    buttonBackground: "#c890b5ff",
    textAccent: "#a37794ff",
    textMyMood: "#A48A97",
    textGeneral: "#544c5bff",
    white: "white",
    number: "black",
    // subtext: "#7d7084ff",
    // primary: "#A48A97",
    // secondary: "#403e4aff",
    // accent: "#c18d9eff",
    // input: "#faecf0e9",
    // bouton: "#ceafbeff",
    // borderInputColor: "#ceafbeff",
    // panel: "#fff",
    // number: "black",
    // moodCard: "#fff",
    // calendarBackground: "#fff",
    // otherdays: "#ceafbeff",
    // textOption: "#c18d9eff",
    // optionBouton: "#fff",
    // grafBackColor: "#fff",
    // grafRules: "#F095C3",
    // grafText: "black",
    // modalBack: "#ffffffe7",
    // textBoutonModal: "#696773",
    // modalText: "#696773",
    // contourGrafCal: "#dcc2d5ff",
    // simple: "black",
    // simpleInv: "white",
  },
};

export const darkTheme = {
  mode: "dark",
  colors: {
    background: "#121314ff",
    cardBackground: "#1c1b1dff", //"#d8becbff",
    inputBackground: "#2f2d31cb",
    buttonBackground: "#a48299ff",
    textAccent: "#a37794ff",
    textMyMood: "#A48A97",
    textGeneral: "#706d75ff",
    white: "black",
    number: "#a37794ff",

    // text: "#A48A97",
    // subtext: "#836876ff",
    // primary: "#725d68ff",
    // secondary: "#605e6aff",
    // input: "#39353ed8",
    // bouton: "#ae97a2ff",
    // borderInputColor: "#917e87ff",
    // accent: "#c18d9eff",
    // panel: "#211f22ff",
    // number: "#c18d9eff",
    // moodCard: "#39353ed8",
    // calendarBackground: "#121314ff",
    // otherdays: "#605e6aff",
    // textOption: "#f4b9cec6",
    // optionBouton: "#39353ed8",
    // grafBackColor: "#211f22ff",
    // grafRules: "#f4b9cec6",
    // grafText: "#f4b9cec6",
    // modalBack: "#3a363ce8",
    // textBoutonModal: "black",
    // modalText: "#f4b9cec6",
    // simple: "white",
    // simpleInv: "black",
    // contourGrafCal: "#211f22ff",
  },
};

export const themes = {
  light: lightTheme,
  dark: darkTheme,
};

export default themes;
